### ISSUE TITLE
Update api

### ISSUE THREAD

**Issue by MatteoTurri** [MatteoTurri/apiseed#10]
Implement update api

It updates a configuration stored in memory.
The provided id should be existing, otherwise the api will return an error

Input: id, name and value provided by the client (partial updates are not allowed)
Output: HTTP 200 Ok or an error if the id is not already existing

**Comment by bytecodeguru** [comment]
There's a typo in
> Output: HTTP 200 Ok or an error if the id is already existing

Probably you mean the contrary.

**Comment by bytecodeguru** [comment]
How should the api behave in the presence of a partial update?
